# Generated by Django 5.0.4 on 2024-05-01 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_podcast_feeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='feeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='podcast', to='core.feeling'),
        ),
    ]
