# Generated by Django 5.0.4 on 2024-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_audiocomment_songcomment_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='quality',
            field=models.CharField(choices=[('khosh', 'خوشحال'), ('khoob', 'خوب'), ('na', 'ناراحت'), ('asab', 'عصبانی')], max_length=10, unique=True),
        ),
    ]
