# Generated by Django 5.0.4 on 2024-05-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feeling_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default=0, upload_to='videos/images/'),
            preserve_default=False,
        ),
    ]
