# Generated by Django 5.0.4 on 2024-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_book_description_alter_podcast_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='description',
        ),
    ]
